version: 2.1

workflows: 
  java-ci: #ワークフローの名前
    jobs:
      - test #ジョブの名前

jobs:
  test: #ジョブの名前
    docker:
      - image: circleci/openjdk:17
    working_directory: ./src
    steps:
      - run: ./mvnw test